name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Android APK with Buildozer Action
        uses: ArtemSzymanski/buildozer-action@v1.2
        id: buildozer
        with:
          command: buildozer android debug
          subfolder: .

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: varna-banker-apk
          path: ${{ steps.buildozer.outputs.filename }}
